spring.application.name=ms-bootcamp
server.port=8082

spring.r2dbc.url=r2dbc:mysql://localhost:3308/db_bootcamp
spring.r2dbc.username=root
spring.r2dbc.password=root

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql